Issue 21 fix standalone
hannemariavister/terraform-nomad-nifiregistry pull request #25
Opened 2021-01-08 12:48 UTC by karimacherradi

## Closes/fixes/resolves issue(s)?
Closes #21 
## What was added/changed/fixed?
- Updated Makefile with option to for nomad to switch to use standalone or standalone with git #21
- updated example/standalone/main.tf with the same switch option #21
- Updated variables.tf and main.tf with new mode-variable #21
- Updated dev/ansible/01_run_terraform.yml #21

## Checklist (after created PR)
- [ ] Added reviewers
- [ ] Added assignee(s)
- [ ] Added label(s)
- [ ] Added to project
- [ ] Added to milestone
- Need to update documentation? (Y/n)

2021-01-08 12:59 UTC, AditiSharma77 commented
could you please give a proper name of this PR , instead of Issue 21 fix standalone .

2021-01-11 06:41 UTC, hannemariavister requested changes

2021-01-11 06:41 UTC, hannemariavister commented on CHANGELOG.md
> +git status
I think this could be removed?

2021-01-11 06:51 UTC, karimacherradi commented on CHANGELOG.md
> +git status
Fix now

2021-01-11 07:05 UTC, hannemariavister approved these changes
Good work 💯

2021-01-11 08:11 UTC, merged